export const GET_ALL_DISHES = 'GET_ALL_DISHES';
export const DETAILS_DISH = 'DETAILS_DISH';
export const POST_USER_CREATE = 'POST_USER_CREATE'
export const LOGIN_USER_JWT = 'LOGIN_USER_JWT'
export const POST_DISH_CREATE = 'POST_DISH_CREATE'
export const GET_USER_WITH_JWT = 'GET_USER_WITH_JWT'
export const GET_LENGTH_CART = "GET_LENGTH_CART"
export const GET_USER_BY_ID = "GET_USER_BY_ID"
export const DELETE_USER = "DELETE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const LOGOUT = "LOGOUT"
export const POST_REVIEWS = "POST_REVIEWS"
export const FILTER = 'FILTER'
export const CREATE_ORDER = "CREATE_ORDER"
export const GET_USER_ORDERS = "GET_USER_ORDERS"
export const GET_NAME_DISHES = "GET_NAME_DISHES"
export const GET_FOOD_REVIEWS = "GET_FOOD_REVIEWS"
export const GET_USERS = "GET_USERS"
export const GET_ALL_TAGS = "GET_ALL_TAGS"
export const LOGIN_WITH_GITHUB = "LOGIN_WITH_GITHUB"
export const IMG_UPDATE_USER = "IMG_UPDATE_USER"






